### ISSUE TITLE
RCS

### ISSUE THREAD

**Issue by LauraSavall** [Skwrr/Dexterion#4] opened 2024-07-10 15:29 UTC
Is it me or is RCS not functional?
Or maybe I didn't configure something right....

Here is my config.json :

{"aimConf":{"aimMode":1,"aimModeMap":{"Closest to Crosshair":1,"Closest to Player":0,"Furthest from crosshair":2,"No preference":3},"aimModes":["Closest to Player","Closest to Crosshair","Furthest from crosshair","No preference"],"bone":0,"boneMap":{"Chest":4,"Crotch":0,"Head":6,"Neck":5},"boneSelect":1,"bones":["Head","Neck","Chest","Crotch"],"checkSpotter":true,"fov":3.309999942779541,"fovCircle":false,"hotAim":0,"hotKey":["SHIFT","ALT","CTRL","Left mouse","Right mouse"],"hotKeyMap":{"ALT":18,"CTRL":17,"Left mouse":1,"Right mouse":2,"SHIFT":16},"hotSelectAim":3,"hotSelectTrigger":1,"hotTrigger":0,"isHotAim":true,"isHotTrigger":true,"playerLock":true,"rcs":true,"sens":2.009999990463257,"smoothing":2.259000062942505,"state":true,"trigger":true},"espConf":{"attributeColours":[1.0,1.0,1.0],"boundBox":false,"boundBoxThickness":1.5,"c4Carrier":true,"c4Colors":[1.0,0.0,0.0],"c4ColorsGradient":[1.0,0.0,0.0],"c4Gradient":false,"c4State":true,"c4Thickness":1.0,"checkSpotted":false,"cornerColours":[1.0,1.0,1.0],"cornerGradient":[1.0,1.0,1.0],"distance":false,"filledBox":true,"filledBoxAlpha":0.20000000298023224,"gradient":false,"head":false,"headColours":[1.0,1.0,1.0],"health":[0.0,0.0,0.0],"hpCounter":true,"isHealthBar":true,"isPawnGun":false,"isPawnName":false,"joint":false,"jointColours":[1.0,1.0,1.0],"notSpottedColours":[0.0,1.0,0.75],"pawnGun":"","pawnName":"","skeleton":false,"skeletonColours":[1.0,1.0,1.0],"snapLines":false,"spottedColours":[0.0,1.0,0.75],"state":true,"width":2.5},"miscConf":{"bunnyHop":false,"deathmatchMode":false,"flash":false,"fov":90,"fovCheck":false,"itemESP":false,"spectator":true}}

**Comment by Skwrr** [comment] 2024-07-10 15:50
Which version is that config, V2?

**Comment by LauraSavall** [comment] 2024-07-10 15:53
> Which version is that config, V2?

I guess, it's when you added the spectator list and c4esp

**Comment by LauraSavall** [comment] 2024-07-10 15:57
Yeah but was using older one

https://github.com/kristofhracza/tim_apple/commit/ccedb3ae15c093c5c561fc8c1dba1537be54fa41

Is the one running on my PC

**Comment by Skwrr** [comment] 2024-07-10 16:00
I think it's v1.
Anyways, the issue is player lock.
Somehow player lock is interfering with RCS (I dont remember make it do that). I'll try to fix it in the next version

**Comment by LauraSavall** [comment] 2024-07-10 16:02
Hum, so if I disable player lock and (nor) aimbot, RCS should work ?

**Comment by Skwrr** [comment] 2024-07-10 16:09
Yes, but your issue is already fixed on V5.
You only have to update your config to match the new version (I might add a config checker system soon)

**Closed by Skwrr** 2024-07-10 16:09 UTC
Labels: bug, on progress

**Comment by Skwrr** [comment] 2024-07-10 16:11
KNOWN ISSUE: Aimbot will 100% glitch out with RCS

**Comment by LauraSavall** [comment] 2024-07-10 16:42
Hum ok, sonV5 fix all, but RCS + AIMBOT isn't compatible for now as it fuckup aimbot ? If I understand well

So for now, only aimbot or RCS should be activated 

What does "player lock" exactly?

**Comment by LauraSavall** [comment] 2024-07-10 17:00
MyBad, awesome work

https://github.com/Skwrr/Dexterion/commit/f039c4a26076f61fe032945e809a3e9e5946d637

**Comment by Skwrr** [comment] 2024-07-11 04:06
> Hum ok, sonV5 fix all, but RCS + AIMBOT isn't compatible for now as it fuckup aimbot ? If I understand well
> 
> So for now, only aimbot or RCS should be activated
> 
> What does "player lock" exactly?

Player lock detect when you target someone while using aimbot, and if another enemy goes inside the FOV circle, it will still target your locked player instead of trying to target both of them at the same time.
